"""
rank.py — ONLINE RANKING ENTRY POINT

Produces submission.csv in ≤ 5 minutes on a 16GB RAM CPU machine.

Pre-requisite: run `python precompute.py` first to build all artifacts.

Usage:
  python rank.py [--data-dir data] [--artifacts-dir artifacts] [--output submission.csv]

Rules (instructions.md §1.1):
  - Zero network calls
  - Zero LLM API calls (reasoning loaded from reasoning.json)
  - No SBERT re-computation (loaded from .npy files)
  - Produces exactly 100 rows, ranks 1–100, score [0.0, 1.0] 4 d.p.
  - Honeypot safety check before writing CSV
"""

import argparse
import json
import os
import sys
import time

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ts() -> str:
    return time.strftime("%H:%M:%S")


def _load_candidates(data_dir: str, project_root: str):
    """
    Load candidate records. Tries data_dir, then project_root for samples.
    Supports .jsonl (one JSON per line) and .json (array).
    """
    search_paths = [
        os.path.join(data_dir, "candidates.jsonl"),
        os.path.join(data_dir, "candidates.json"),
        os.path.join(project_root, "sample_candidates.json"),
    ]
    for path in search_paths:
        if not os.path.exists(path):
            continue
        print(f"[{_ts()}] Loading candidates from '{path}'...")
        t0 = time.time()
        if path.endswith(".jsonl"):
            candidates = []
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        candidates.append(json.loads(line))
        else:
            with open(path, "r", encoding="utf-8") as f:
                candidates = json.load(f)
        print(f"[{_ts()}] Loaded {len(candidates):,} candidates in {time.time()-t0:.1f}s.")
        return candidates

    raise FileNotFoundError(
        f"No candidate data found. Searched: {search_paths}"
    )


def _load_artifacts(artifacts_dir: str):
    """
    Load all pre-computed artifacts from disk.
    Raises FileNotFoundError with instructions if any artifact is missing.
    """
    required = {
        "jd_parsed.json":          "Stage 0",
        "features.parquet":        "Stage 2",
        "career_embeddings.npy":   "Stage 3",
        "skills_embeddings.npy":   "Stage 3",
        "jd_vector.npy":           "Stage 0/3",
        "candidate_ids.json":      "Stage 3",
        "career_texts.json":       "Stage 3",
        "reasoning.json":          "Stage 8",
    }
    missing = [
        f"  {f} (generated by {stage})"
        for f, stage in required.items()
        if not os.path.exists(os.path.join(artifacts_dir, f))
    ]
    if missing:
        raise FileNotFoundError(
            "rank.py: Missing pre-computed artifacts:\n"
            + "\n".join(missing)
            + "\n\nFix: run `python precompute.py` first."
        )

    t0 = time.time()
    print(f"[{_ts()}] Loading artifacts from '{artifacts_dir}'...")

    with open(os.path.join(artifacts_dir, "jd_parsed.json"), "r") as f:
        jd_parsed = json.load(f)

    features_df = pd.read_parquet(os.path.join(artifacts_dir, "features.parquet"))

    career_emb = np.load(os.path.join(artifacts_dir, "career_embeddings.npy"))
    skills_emb = np.load(os.path.join(artifacts_dir, "skills_embeddings.npy"))
    jd_vec = np.load(os.path.join(artifacts_dir, "jd_vector.npy"))

    with open(os.path.join(artifacts_dir, "candidate_ids.json"), "r") as f:
        embedding_cids = json.load(f)

    with open(os.path.join(artifacts_dir, "career_texts.json"), "r") as f:
        career_texts = json.load(f)

    with open(os.path.join(artifacts_dir, "reasoning.json"), "r") as f:
        reasoning = json.load(f)

    elapsed = time.time() - t0
    print(
        f"[{_ts()}] Artifacts loaded in {elapsed:.1f}s. "
        f"features: {len(features_df):,} rows, "
        f"embeddings: {len(embedding_cids):,} candidates, "
        f"reasoning: {len(reasoning)} entries."
    )
    return jd_parsed, features_df, career_emb, skills_emb, jd_vec, embedding_cids, career_texts, reasoning


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="RecruitRank — Produce submission.csv in ≤ 5 minutes."
    )
    parser.add_argument("--data-dir", default="data",
                        help="Directory containing candidates.json/jsonl (default: data/)")
    parser.add_argument("--artifacts-dir", default="artifacts",
                        help="Directory with pre-computed artifacts (default: artifacts/)")
    parser.add_argument("--output", default="submission.csv",
                        help="Output CSV path (default: submission.csv)")
    args = parser.parse_args()

    project_root = os.path.dirname(os.path.abspath(__file__))
    artifacts_dir = os.path.join(project_root, args.artifacts_dir)
    data_dir = os.path.join(project_root, args.data_dir)

    t_wall_start = time.time()

    print("=" * 60)
    print("RecruitRank — rank.py")
    print(f"  data_dir     : {data_dir}")
    print(f"  artifacts_dir: {artifacts_dir}")
    print(f"  output       : {args.output}")
    print("=" * 60)

    # -----------------------------------------------------------------------
    # Load artifacts (< 30s target per instructions.md §11.1)
    # -----------------------------------------------------------------------
    (jd_parsed, features_df, career_emb, skills_emb, jd_vec,
     embedding_cids, career_texts, reasoning) = _load_artifacts(artifacts_dir)

    # -----------------------------------------------------------------------
    # Load raw candidates
    # -----------------------------------------------------------------------
    candidates = _load_candidates(data_dir, project_root)
    candidates_dict = {c["candidate_id"]: c for c in candidates}

    # -----------------------------------------------------------------------
    # Stage 1: Hard Filters + Honeypot Gate (< 5s target)
    # -----------------------------------------------------------------------
    from pipeline.stage1_filters import apply_hard_filters, apply_honeypot_gate

    print(f"[{_ts()}] Stage 1: Hard Filters + Honeypot Gate...")
    t1 = time.time()
    filtered = apply_hard_filters(candidates, jd_parsed)
    gated = apply_honeypot_gate(filtered)
    honeypot_ids = {c["candidate_id"] for c in gated if c.get("honeypot_flag", False)}
    valid_ids = {c["candidate_id"] for c in gated if not c.get("honeypot_flag", False)}
    print(
        f"[{_ts()}] Stage 1: Complete in {time.time()-t1:.1f}s. "
        f"{len(candidates):,} raw → {len(gated):,} survived Pass A. "
        f"Honeypots: {len(honeypot_ids):,}. Valid: {len(valid_ids):,}."
    )

    # -----------------------------------------------------------------------
    # Stage 4: Weighted Score Combiner (< 10s target)
    # -----------------------------------------------------------------------
    from pipeline.stage4_scorer import compute_weighted_scores

    print(f"[{_ts()}] Stage 4: Weighted Score Combiner...")
    t4 = time.time()

    # Use only non-honeypot features that also have embeddings
    valid_features_df = features_df[
        features_df["candidate_id"].isin(valid_ids)
    ].copy()

    scored_df = compute_weighted_scores(
        valid_features_df, career_emb, skills_emb, jd_vec, embedding_cids
    )
    print(f"[{_ts()}] Stage 4: Complete in {time.time()-t4:.1f}s. {len(scored_df):,} candidates scored.")

    # -----------------------------------------------------------------------
    # Stage 5: Behavioral Signal Modifier (< 10s target)
    # -----------------------------------------------------------------------
    from pipeline.stage5_behavioral import apply_behavioral_modifier

    print(f"[{_ts()}] Stage 5: Behavioral Signal Modifier...")
    t5 = time.time()
    scored_cids = set(scored_df["candidate_id"])
    scored_candidates = [c for c in candidates if c["candidate_id"] in scored_cids]
    final_df = apply_behavioral_modifier(scored_df, scored_candidates)

    # --- HONEYPOT SAFETY: zero out final_base_score for honeypots (should be none, just in case) ---
    final_df["honeypot_flag"] = final_df["candidate_id"].isin(honeypot_ids)
    final_df.loc[final_df["honeypot_flag"], "final_base_score"] = 0.0
    print(f"[{_ts()}] Stage 5: Complete in {time.time()-t5:.1f}s.")

    # -----------------------------------------------------------------------
    # Stage 6: ANN Retrieval → Top 500 (< 5s target)
    # -----------------------------------------------------------------------
    from pipeline.stage6_retrieval import retrieve_top_500

    top_500 = retrieve_top_500(final_df)

    # -----------------------------------------------------------------------
    # Stage 7: Cross-Encoder Reranking → Top 100 (< 2 min target)
    # -----------------------------------------------------------------------
    from pipeline.stage7_crossencoder import run_stage7

    top_100 = run_stage7(top_500, artifacts_dir=artifacts_dir)

    # -----------------------------------------------------------------------
    # Honeypot Safety Check (instructions.md §4.3) — BEFORE writing CSV
    # -----------------------------------------------------------------------
    top_100["honeypot_flag"] = top_100["candidate_id"].isin(honeypot_ids)
    honeypot_in_top = top_100["honeypot_flag"].sum()
    if honeypot_in_top > 0:
        raise RuntimeError(
            f"ABORT: {honeypot_in_top} honeypot(s) detected in top 100. "
            "This would trigger competition disqualification. "
            "Fix honeypot detection in Stage 1 before submitting."
        )

    # -----------------------------------------------------------------------
    # Build submission DataFrame
    # -----------------------------------------------------------------------
    print(f"[{_ts()}] Building submission.csv...")

    # Attach reasoning strings (pre-computed in Stage 8)
    top_100["reasoning"] = top_100["candidate_id"].map(reasoning)

    # Fill any candidates not in reasoning.json with a safe fallback
    missing_reasoning = top_100["reasoning"].isna()
    if missing_reasoning.any():
        missing_cids = top_100.loc[missing_reasoning, "candidate_id"].tolist()
        print(
            f"[{_ts()}] WARNING: {len(missing_cids)} candidates have no reasoning "
            f"in reasoning.json (precompute was likely run on a different candidate set). "
            f"Using fallback template."
        )
        from pipeline.stage8_reasoning import generate_fallback_reasoning
        from pipeline.stage0_jd_parser import parse_jd
        for cid in missing_cids:
            cand = candidates_dict.get(cid, {"candidate_id": cid, "profile": {}})
            rank = int(top_100.loc[top_100["candidate_id"] == cid, "rank"].values[0])
            fb = generate_fallback_reasoning(cand, rank, jd_parsed)
            top_100.loc[top_100["candidate_id"] == cid, "reasoning"] = fb

    # Round scores to 4 decimal places per instructions.md §9.3
    top_100["score"] = top_100["final_score"].round(4)

    # Final sort: descending score, ascending candidate_id for tiebreaking
    top_100 = top_100.sort_values(
        ["score", "candidate_id"], ascending=[False, True]
    ).reset_index(drop=True)
    top_100["rank"] = range(1, len(top_100) + 1)

    # -----------------------------------------------------------------------
    # Output validation (instructions.md §12.3 — fail loudly)
    # -----------------------------------------------------------------------
    if len(top_100) != 100:
        print(f"[{_ts()}] WARNING: Expected 100 rows, got {len(top_100)}. "
              "This is fine for testing with small sample sets.")
    
    assert top_100["rank"].tolist() == list(range(1, len(top_100) + 1)), (
        "Ranks are not sequential starting from 1. This is a bug."
    )
    assert (top_100["score"] >= 0.0).all() and (top_100["score"] <= 1.0).all(), (
        f"Scores out of [0.0, 1.0] range. Min={top_100['score'].min():.4f}, "
        f"Max={top_100['score'].max():.4f}."
    )
    assert top_100["score"].is_monotonic_decreasing or (
        top_100["score"].diff().dropna() <= 1e-9
    ).all(), (
        "Scores are not non-increasing. Tiebreak sort may have failed."
    )

    # Reasoning length check
    long_reasoning = top_100[top_100["reasoning"].str.len() > 300]
    if not long_reasoning.empty:
        for _, row in long_reasoning.iterrows():
            top_100.loc[top_100["candidate_id"] == row["candidate_id"], "reasoning"] = (
                row["reasoning"][:297] + "..."
            )

    # -----------------------------------------------------------------------
    # Write submission.csv
    # -----------------------------------------------------------------------
    output_cols = ["candidate_id", "rank", "score", "reasoning"]
    output_df = top_100[output_cols].copy()
    output_path = os.path.join(project_root, args.output)
    output_df.to_csv(output_path, index=False, encoding="utf-8")
    print(f"[{_ts()}] Wrote {len(output_df)} rows to '{output_path}'.")

    # -----------------------------------------------------------------------
    # Run official validator
    # -----------------------------------------------------------------------
    validator_path = os.path.join(project_root, "validate_submission.py")
    if os.path.exists(validator_path):
        print(f"[{_ts()}] Running validate_submission.py...")
        from validate_submission import validate_submission
        errors = validate_submission(output_path)
        if errors:
            print(f"\nValidation FAILED ({len(errors)} error(s)):")
            for e in errors:
                print(f"  - {e}")
            sys.exit(1)
        else:
            print(f"[{_ts()}] validate_submission.py: PASSED ✓")
    else:
        print(f"[{_ts()}] validate_submission.py not found — skipping external validation.")

    # -----------------------------------------------------------------------
    # Final timing
    # -----------------------------------------------------------------------
    elapsed = time.time() - t_wall_start
    print()
    print("=" * 60)
    print(f"rank.py complete in {elapsed:.1f}s ({elapsed/60:.2f} min).")
    if elapsed > 300:
        print("WARNING: Exceeded 5-minute wall clock budget!")
    print(f"Submission: {output_path}")
    print()
    print("Top 5 candidates:")
    for _, row in output_df.head(5).iterrows():
        print(f"  [{row['rank']:3d}] {row['candidate_id']}  score={row['score']:.4f}  {row['reasoning'][:60]}...")
    print("=" * 60)


if __name__ == "__main__":
    main()
